In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')


In [2]:
data = pd.read_csv('admitance.csv')

In [3]:
data

SAT Admitted
0    1363       No
1    1792      Yes
2    1954      Yes
3    1653       No
4    1593       No
..    ...      ...
163  1722      Yes
164  1750      Yes
165  1555       No
166  1524       No
167  1461       No

[168 rows x 2 columns]

In [4]:
data['Admitted'] = data['Admitted'].map({'Yes':1,'No':0})

In [5]:
data

SAT  Admitted
0    1363         0
1    1792         1
2    1954         1
3    1653         0
4    1593         0
..    ...       ...
163  1722         1
164  1750         1
165  1555         0
166  1524         0
167  1461         0

[168 rows x 2 columns]

In [6]:
X = data['SAT']

In [7]:
X

0      1363
1      1792
2      1954
3      1653
4      1593
       ... 
163    1722
164    1750
165    1555
166    1524
167    1461
Name: SAT, Length: 168, dtype: int64

In [8]:
X = np.array(X).reshape(-1,1)

In [9]:
X

array([[1363],
       [1792],
       [1954],
       [1653],
       [1593],
       [1755],
       [1775],
       [1887],
       [1893],
       [1580],
       [1857],
       [1880],
       [1664],
       [1364],
       [1693],
       [1850],
       [1633],
       [1634],
       [1636],
       [1855],
       [1987],
       [1997],
       [1422],
       [1508],
       [1720],
       [1879],
       [1634],
       [1802],
       [1849],
       [1764],
       [1460],
       [1675],
       [1656],
       [2020],
       [1850],
       [1865],
       [1664],
       [1872],
       [1654],
       [1393],
       [1587],
       [1631],
       [1931],
       [1370],
       [1810],
       [1414],
       [1761],
       [1477],
       [1486],
       [1561],
       [1549],
       [2050],
       [1697],
       [1543],
       [1934],
       [1385],
       [1670],
       [1735],
       [1634],
       [1777],
       [1550],
       [1715],
       [1925],
       [1842],
       [1786],
       [1435],
       [13

In [10]:
y = data['Admitted']

In [11]:
y

0      0
1      1
2      1
3      0
4      0
      ..
163    1
164    1
165    0
166    0
167    0
Name: Admitted, Length: 168, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [14]:
X_train

array([[1715],
       [1810],
       [1720],
       [1842],
       [1687],
       [1855],
       [1674],
       [1702],
       [1412],
       [1633],
       [1387],
       [1974],
       [1587],
       [2020],
       [1422],
       [1634],
       [1964],
       [1572],
       [1526],
       [1464],
       [1802],
       [1674],
       [1730],
       [1720],
       [1455],
       [1934],
       [1636],
       [1861],
       [1555],
       [1460],
       [1679],
       [1925],
       [1954],
       [1777],
       [1666],
       [1735],
       [1370],
       [1857],
       [1542],
       [1808],
       [1741],
       [1764],
       [1831],
       [1492],
       [1934],
       [1549],
       [1591],
       [1893],
       [1786],
       [1721],
       [1662],
       [1435],
       [1561],
       [1486],
       [2015],
       [1364],
       [1962],
       [1508],
       [1891],
       [1987],
       [1850],
       [1907],
       [1697],
       [1469],
       [1653],
       [1461],
       [13

In [15]:
X_train.shape

(134, 1)

In [16]:
X_test.shape

(34, 1)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
log_reg = LogisticRegression()

In [19]:
log_reg.fit(X_train,y_train)

LogisticRegression()

In [20]:
# testing

In [21]:
y_pred = log_reg.predict(X_test)

In [22]:
y_pred

array([1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1], dtype=int64)

In [23]:
y_test

151    1
56     0
123    0
60     0
100    1
51     1
7      1
5      1
86     0
135    0
54     1
94     0
157    1
101    0
73     1
45     0
74     1
97     0
139    0
96     1
107    1
106    1
150    1
166    0
55     0
152    1
26     1
143    1
155    0
33     1
8      1
108    0
122    0
37     1
Name: Admitted, dtype: int64

In [24]:
# evaluation

In [25]:
# confusion matrix & classification report

In [26]:
from sklearn.metrics import confusion_matrix

In [27]:
print(confusion_matrix(y_test,y_pred))

[[14  1]
 [ 1 18]]


In [28]:
from sklearn.metrics import classification_report

In [29]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.93      0.93        15
           1       0.95      0.95      0.95        19

    accuracy                           0.94        34
   macro avg       0.94      0.94      0.94        34
weighted avg       0.94      0.94      0.94        34

